In [1]:
import pandas as pd
import numpy as np

# import data

In [2]:
drawing_order = pd.read_csv('input.txt',header=None).iloc[0]
drawing_order.head()

0      73
1    42.0
2    95.0
3    35.0
4    13.0
Name: 0, dtype: object

In [3]:
boards = pd.read_csv('input.txt', header=None, skiprows=2, skip_blank_lines=True, sep='\s+')

boards.head(6)

0   1   2   3   4
0  91   5  64  81  34
1  15  99  31  63  65
2  45  39  54  93  83
3  51  14  23  86  32
4  19  22  16  13   3
5  20  83  38  85  70

# Create 3D array with boards

In [4]:
dimensions_board = 5
boards_list = np.array([[[0]*dimensions_board]*dimensions_board] * int(boards.count().values[0]/dimensions_board))
for board_i, _ in enumerate(boards_list):
    boards_list[board_i] = boards.loc[5*board_i:5*(board_i+1)-1]
original_boards_list = boards_list.copy()

# Find winning board

### mark crossed number with -1

In [5]:
stop_drawing = False
for drawn_number in drawing_order:
    idx = boards_list==int(drawn_number)
    boards_list[idx] = np.array([-1]*sum(sum(sum(idx))))
    # check for all boards if any line or column is completely crossed
    for idx, board_i in enumerate(boards_list):
        if any(np.sum(board_i,0) ==-5) or any(np.sum(board_i,1) ==-5):
            stop_drawing = True
            break
    if stop_drawing:
        break
score = np.sum(board_i[board_i>-1],None) * drawn_number
print(f"number drawn: {drawn_number}, boards_i: {board_i}, score: {score}")
        
        


number drawn: 71.0, boards_i: [[64 65  6 86 53]
 [10 56  2 88 -1]
 [11 -1 -1 84 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 19 14  4]], score: 39902.0


# Part B

In [14]:
original_boards_list

array([[[91,  5, 64, 81, 34],
        [15, 99, 31, 63, 65],
        [45, 39, 54, 93, 83],
        [51, 14, 23, 86, 32],
        [19, 22, 16, 13,  3]],

       [[20, 83, 38, 85, 70],
        [69, 12, 14, 26, 84],
        [19, 76, 45, 78, 99],
        [22, 80, 90, 33, 46],
        [75, 31, 21,  6, 28]],

       [[22, 52, 65, 75,  2],
        [91, 12, 45, 18, 94],
        [38, 66, 85, 39,  1],
        [24, 36, 55, 74,  3],
        [89, 14, 79, 99, 48]],

       ...,

       [[73, 81, 41, 54, 92],
        [70, 39, 66, 38, 27],
        [89, 15, 80, 22, 87],
        [36, 12, 48, 93, 26],
        [44, 85, 19, 60, 49]],

       [[ 8, 28, 76, 19,  5],
        [86, 34, 50, 98, 29],
        [80, 91, 46, 90, 40],
        [33, 58, 21, 22, 49],
        [64, 41, 87, 92, 72]],

       [[16, 61, 73, 82, 25],
        [ 8,  1, 53, 10, 71],
        [47, 99, 90, 93, 39],
        [87, 74, 41, 52, 69],
        [17, 49, 91, 30, 33]]])

In [29]:
boards_list_b = original_boards_list.copy()
stop_drawing = False
boards_that_did_not_yet_win = np.ones(len(boards_list_b))
for drawn_number in drawing_order:
    idx = boards_list_b==int(drawn_number)
    boards_list_b[idx] = np.array([-1]*sum(sum(sum(idx))))
    # check for all boards if any line or column is completely crossed
    for idx2, board_i in enumerate(boards_list_b):
        if boards_that_did_not_yet_win[idx2] == 1:
            if any(np.sum(board_i,0) ==-5) or any(np.sum(board_i,1) ==-5):
                boards_that_did_not_yet_win[idx2] = 0
        if np.all(boards_that_did_not_yet_win==0):
            break
    
    if np.all(boards_that_did_not_yet_win==0):
        break
score = np.sum(board_i[board_i>-1],None) * drawn_number
print(f"number drawn: {drawn_number}, boards_i: {board_i}, score: {score}")

number drawn: 56.0, boards_i: [[-1 -1 -1 -1 32]
 [-1 -1 38 -1 45]
 [70 -1 -1 86 -1]
 [-1 -1 -1 66 60]
 [-1 -1 84 -1 -1]], score: 26936.0


In [25]:
boards_list

array([[[-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       ...,

       [[-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1]]])

In [17]:
idx

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       ...,

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, Fals