In [2]:
import pandas as pd
import numpy as np
import re


# import data

In [3]:
example = pd.read_csv('example.txt',header=None, sep=',', engine='python').values.astype(np.int8)
example

array([[3, 4, 3, 1, 2]], dtype=int8)

In [4]:
original_input = pd.read_csv('input.txt',header=None, sep=',', engine='python').values.astype(np.int8)
original_input

array([[1, 4, 2, 4, 5, 3, 5, 2, 2, 5, 2, 1, 2, 4, 5, 2, 3, 5, 4, 3, 3, 1,
        2, 3, 2, 1, 4, 4, 2, 1, 1, 4, 1, 4, 4, 4, 1, 4, 2, 4, 3, 3, 3, 3,
        1, 1, 5, 4, 2, 5, 2, 4, 2, 2, 3, 1, 2, 5, 2, 4, 1, 5, 3, 5, 1, 4,
        5, 3, 1, 4, 5, 2, 4, 5, 3, 1, 2, 5, 1, 2, 2, 1, 5, 5, 1, 1, 1, 4,
        2, 5, 4, 3, 3, 1, 3, 4, 1, 1, 2, 2, 2, 5, 4, 4, 3, 2, 1, 1, 1, 1,
        2, 5, 1, 3, 2, 1, 4, 4, 2, 1, 4, 5, 2, 5, 5, 3, 3, 1, 3, 2, 2, 3,
        4, 1, 3, 1, 5, 4, 2, 5, 2, 4, 1, 5, 1, 4, 5, 1, 2, 4, 4, 1, 4, 1,
        4, 4, 2, 2, 5, 4, 1, 3, 1, 3, 3, 1, 5, 1, 5, 5, 5, 1, 3, 1, 2, 1,
        4, 5, 4, 4, 1, 3, 3, 1, 4, 1, 2, 1, 3, 2, 1, 5, 5, 3, 3, 1, 3, 5,
        1, 5, 3, 5, 3, 1, 1, 1, 1, 4, 4, 3, 5, 5, 1, 1, 2, 2, 5, 5, 3, 2,
        5, 2, 3, 4, 4, 1, 1, 2, 2, 4, 3, 5, 5, 1, 1, 5, 4, 3, 1, 3, 1, 2,
        4, 4, 4, 4, 1, 4, 3, 4, 1, 3, 5, 5, 5, 1, 3, 5, 4, 3, 1, 3, 5, 4,
        4, 3, 4, 2, 1, 1, 3, 1, 1, 2, 4, 1, 4, 1, 1, 1, 5, 5, 1, 3, 4, 1,
        1, 5, 4, 4, 2, 2, 1, 3, 4, 4, 

# Part 1
## Example

In [5]:
population = example.copy()
for day in range(80):
    population = population - 1
    # they need to reproduce at 0, but use -1 here because
    # this avoids make if statement to ensure they either reduce by 1 or
    # reproduce (they should not reproduce and decrease by 1).
    born_event = population==-1
    number_of_new_borns = born_event.sum(None)
    new_borns = 8 * np.ones(number_of_new_borns)
    population[born_event] = 6
    population = np.append(population, new_borns)
    # print(f'Population at Day {day+1}: {population}')
len(population)



5934

## Actual assignment

In [6]:
population = original_input.copy()
for day in range(80):
    population = population - 1
    # they need to reproduce at 0, but use -1 here because
    # this avoids make if statement to ensure they either reduce by 1 or
    # reproduce (they should not reproduce and decrease by 1).
    born_event = population==-1
    number_of_new_borns = born_event.sum(None)
    new_borns = 8 * np.ones(number_of_new_borns)
    population[born_event] = 6
    population = np.append(population, new_borns)
    # print(f'Population at Day {day+1}: {population}')
len(population)

349549

# Part B

Part A could be done in brute force, but part B has a memory error. So I switched here to a histogram which is much more efficient

## Example
### Example output

In [81]:
print(f'''dag 0: {np.histogram([3,4,3,1,2], bins=range(10))[0]}
dag 1: {np.histogram([2,3,2,0,1], bins=range(10))[0]}
dag 2: {np.histogram([1,2,1,6,0,8], bins=range(10))[0]}
dag 3: {np.histogram([0,1,0,5,6,7,8], bins=range(10))[0]}
dag 4: {np.histogram([6,0,6,4,5,6,7,8,8], bins=range(10))[0]}
dag 5: {np.histogram([5,6,5,3,4,5,6,7,7,8], bins=range(10))[0]}
dag 6: {np.histogram([4,5,4,2,3,4,5,6,6,7], bins=range(10))[0]}
dag 7: {np.histogram([3,4,3,1,2,3,4,5,5,6], bins=range(10))[0]}
dag 8: {np.histogram([2,3,2,0,1,2,3,4,4,5], bins=range(10))[0]}''')

dag 0: [0 1 1 2 1 0 0 0 0]
dag 1: [1 1 2 1 0 0 0 0 0]
dag 2: [1 2 1 0 0 0 1 0 1]
dag 3: [2 1 0 0 0 1 1 1 1]
dag 4: [1 0 0 0 1 1 3 1 2]
dag 5: [0 0 0 1 1 3 2 2 1]
dag 6: [0 0 1 1 3 2 2 1 0]
dag 7: [0 1 1 3 2 2 1 0 0]
dag 8: [1 1 3 2 2 1 0 0 0]


### Example run

In [83]:
population = example.copy()
population_hist, histogram_bin_edges = np.histogram(population, bins=range(10))

# print(population_hist)
hist0_yesterday = population_hist[0]
for day in range(80):
    for bin_i in range(len(population_hist)):
        if bin_i >0:# len(population_hist):
            # counts down: lower bin gets value of higher bin
            population_hist[bin_i-1] = population_hist[bin_i]
    population_hist[6] += hist0_yesterday
    population_hist[8] = hist0_yesterday
    hist0_yesterday = population_hist[0]
    # print(population_hist)
sum(population_hist)

5934

## Real data run

In [84]:
population = original_input.copy()
population_hist, histogram_bin_edges = np.histogram(population, bins=range(10))

print(population_hist)
hist0_yesterday = population_hist[0]
for day in range(80):
    for bin_i in range(len(population_hist)):
        if bin_i >0:# len(population_hist):
            # counts down: lower bin gets value of higher bin
            population_hist[bin_i-1] = population_hist[bin_i]
    population_hist[6] += hist0_yesterday
    population_hist[8] = hist0_yesterday
    hist0_yesterday = population_hist[0]
    # print(population_hist)
sum(population_hist)

[ 0 80 53 51 63 53  0  0  0]


349549

In [88]:
population = original_input.copy()
population_hist, histogram_bin_edges = np.histogram(population, bins=range(10))

# print(population_hist)
hist0_yesterday = population_hist[0]
for day in range(256 ):
    for bin_i in range(len(population_hist)):
        if bin_i >0:# len(population_hist):
            # counts down: lower bin gets value of higher bin
            population_hist[bin_i-1] = population_hist[bin_i]
    population_hist[6] += hist0_yesterday
    population_hist[8] = hist0_yesterday
    hist0_yesterday = population_hist[0]
    # print(population_hist)
sum(population_hist)

1589590444365