In [1]:
import pandas as pd
import numpy as np
import re


# import data

In [29]:
example = pd.read_csv('example.txt',header=None, sep=',', engine='python').values[0]
example

array([16,  1,  2,  0,  4,  2,  7,  1,  2, 14], dtype=int64)

In [30]:
original_input = pd.read_csv('input.txt',header=None, sep=',', engine='python').values[0]
original_input

array([1101,    1,   29,   67, 1102,    0,    1,   65, 1008,   65,   35,
         66, 1005,   66,   28,    1,   67,   65,   20,    4,    0, 1001,
         65,    1,   65, 1106,    0,    8,   99,   35,   67,  101,   99,
        105,   32,  110,   39,  101,  115,  116,   32,  112,   97,  115,
         32,  117,  110,  101,   32,  105,  110,  116,   99,  111,  100,
        101,   32,  112,  114,  111,  103,  114,   97,  109,   10,   14,
         94,  153,  512, 1778, 1219,  522,  207,  112,  148, 1185,  380,
        530,  502,  957,  898,   71,   10,  719,   47,   51,  188,  188,
       1277,  446,  156,  188,  990,  370,  549, 1086,   49,  150,   42,
         50,  976,  456,   24,  526,  183,  206,  887,    3,  487,   11,
        111,  933, 1059,   51,  439,   30,  258,  901,   19, 1207,  718,
        404,  498,   79,   83,   58,  520,  267,  109,  933,    4,  174,
        748,   66,  463,  514,  378,  708,  103, 1073,  364,  224,  254,
         28,  196,   95,   30,  567,  633,  943,   

# Part A
## Example

In [31]:
positions = example.copy()
costs = np.zeros(max(positions))
costs
# BRUTE FORCE: loop over all positions, calculate the cost to move all crabs there
for position_i in range(len(costs)):
    costs[position_i] =sum(abs(positions - position_i))
    # print(f'Population at Day {day+1}: {population}')
costs


array([ 49.,  41.,  37.,  39.,  41.,  45.,  49.,  53.,  59.,  65.,  71.,
        77.,  83.,  89.,  95., 103.])

## Actual assignment

In [32]:
positions = original_input.copy()
costs = np.zeros(max(positions))
# BRUTE FORCE: loop over all positions, calculate the cost to move all crabs there
for position_i in range(len(costs)):
    costs[position_i] =sum(abs(positions - position_i))
    # print(f'Population at Day {day+1}: {population}')
min(costs)


351901.0

# Part B

## Example
### Example output

### Example run

In [47]:
positions = example.copy()
costs = np.zeros(max(positions))
costs
# BRUTE FORCE: loop over all positions, calculate the cost to move all crabs there
for position_i in range(len(costs)):
    movement = abs(positions - position_i)
    cost = np.zeros(len(movement))
    for crab_i, crab_movement in enumerate(movement):
        cost[crab_i] = sum(range(1,crab_movement+1))
    costs[position_i] =sum(cost)
costs


array([290., 242., 206., 183., 170., 168., 176., 194., 223., 262., 311.,
       370., 439., 518., 607., 707.])

## Real data run

In [48]:
positions = example.copy()
costs = np.zeros(max(positions))
costs
# BRUTE FORCE: loop over all positions, calculate the cost to move all crabs there
for position_i in range(len(costs)):
    movement = abs(positions - position_i)
    cost = np.zeros(len(movement))
    for crab_i, crab_movement in enumerate(movement):
        cost[crab_i] = sum(range(1,crab_movement+1))
    costs[position_i] =sum(cost)
costs


array([290., 242., 206., 183., 170., 168., 176., 194., 223., 262., 311.,
       370., 439., 518., 607., 707.])

In [50]:
positions = original_input.copy()
costs = np.zeros(max(positions))
costs
# BRUTE FORCE: loop over all positions, calculate the cost to move all crabs there
for position_i in range(len(costs)):
    movement = abs(positions - position_i)
    cost = np.zeros(len(movement))
    for crab_i, crab_movement in enumerate(movement):
        cost[crab_i] = sum(range(1,crab_movement+1))
    costs[position_i] =sum(cost)
min(costs)


101079875.0